# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        read_model_connection:
            timestampable: true  # Авто created_at, updated_at
            softdeleteable: true  # Авто deleted_at для soft delete
            # Другие: sluggable: true, loggable: true и т.д., если нужно
